### ISSUE TITLE
vcsim: parse error on virtualmachine config properties

### ISSUE THREAD

**Issue by jctanner** [vmware/govmomi#856] opened 2017-10-04 03:01 UTC
```bash
$ ./testcase.py
'vim.VirtualMachine:virtualmachine-61'
Traceback (most recent call last):
  File "./testcase.py", line 48, in <module>
    main()
  File "./testcase.py", line 44, in main
    pprint(vm.config)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 574, in __call__
    return self.f(*args, **kwargs)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 394, in _InvokeAccessor
    return self._stub.InvokeAccessor(self, info)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/StubAdapterAccessorImpl.py", line 42, in InvokeAccessor
    options=self._pcType.RetrieveOptions(maxObjects=1))
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 580, in <lambda>
    self.f(*(self.args + (obj,) + args), **kwargs)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/VmomiSupport.py", line 386, in _InvokeMethod
    return self._stub.InvokeMethod(self, info, args)
  File "/home/jtanner/.local/lib/python2.7/site-packages/pyVmomi/SoapAdapter.py", line 1357, in InvokeMethod
    raise exc
pyVmomi.SoapAdapter.ParserError: 'xml document: <httplib.HTTPResponse instance at 0x7fc94903f710> parse error at: line:2, col:5161'
```

Testcase to reproduce this with the most current version of pyvmomi (6.5.0.2017.5.post1) ...

```python
#!/usr/bin/env python

# testcase.py

import ssl

from pprint import pprint
from pyVim import connect
from pyVmomi import vim


def get_obj(content, vimtype, name):
    """
    Return an object by name, if name is None the
    first found object is returned
    """
    obj = None
    container = content.viewManager.CreateContainerView(
        content.rootFolder, vimtype, True)
    for c in container.view:
        if name:
            if c.name == name:
                obj = c
                break
        else:
            obj = c
            break

    return obj


def main():

    service_instance = connect.SmartConnect(host='127.0.0.1', port=8989, user='user', pwd='pass')
    content = service_instance.RetrieveContent()

    # /F0/DC0/vm/F0/DC0_H0_VM0
    vm = get_obj(content, [vim.VirtualMachine], 'DC0_H0_VM0')
    pprint(vm)
    pprint(vm.config)


if __name__ == "__main__":
    main()
```

Diff of the xml response (used -trace on vcsim to capture the xml) with a previous version of vcsim versus current ...

```diff
$ diff _good.xml _bad.xml
12c12
<               <modified>2017-10-04T02:52:37.257972029Z</modified>
---
>               <modified>2017-10-03T21:53:48.396838888-04:00</modified>
16c16
<               <uuid>aff5e221-48c2-44a4-8922-7f337a254bd5</uuid>
---
>               <uuid>e9f8212c-09d8-4679-acc2-4b9530cc532b</uuid>
141c141
<                     <deviceName>cdrom--201-842352752816</deviceName>
---
>                     <deviceName>cdrom--201-842352858480</deviceName>
151a152,167
>                 <device XMLSchema-instance:type="VirtualDisk">
>                   <key>204</key>
>                   <deviceInfo XMLSchema-instance:type="Description">
>                     <label>disk--201-0</label>
>                     <summary>disk--201-0</summary>
>                   </deviceInfo>
>                   <backing XMLSchema-instance:type="VirtualDiskFlatVer2BackingInfo">
>                     <fileName>[LocalDS_0] DC0_H0_VM0/disk1.vmdk</fileName>
>                     <datastore type=""/>
>                     <diskMode>persistent</diskMode>
>                     <thinProvisioned>true</thinProvisioned>
>                   </backing>
>                   <controllerKey>-201</controllerKey>
>                   <unitNumber>0</unitNumber>
>                   <capacityInKB>0</capacityInKB>
>                 </device>
156c172
<                     <summary>DVSwitch: 9cfedc33-9b54-4f21-a1e1-418d6cb102ac</summary>
---
>                     <summary>DVSwitch: de94fef8-be1b-44ee-8369-8d25b486da7f</summary>
160c176
<                       <switchUuid>9cfedc33-9b54-4f21-a1e1-418d6cb102ac</switchUuid>
---
>                       <switchUuid>de94fef8-be1b-44ee-8369-8d25b486da7f</switchUuid>
176c192
<                   <macAddress>00:0c:29:cf:01:8f</macAddress>
---
>                   <macAddress>00:0c:29:48:ee:c7</macAddress>
```

**Comment by jctanner** [comment] 2017-10-04 03:02
It seems as if the new virtualdisk property is likely at fault here. I'm not savvy enough to really understand the deserialization problem but does this possibly have something to do with the wsdl vcsim serves not providing an object type within virtualdisk?

**Comment by jctanner** [comment] 2017-10-04 03:06
cc @Akasurde

**Comment by Akasurde** [comment] 2017-10-04 11:48
@anfernee Could you please look into this as this seems to be a regression ?

**Comment by dougm** [comment] 2017-10-04 13:18
@jctanner thanks for the detailed report and test case to reproduce!

**Comment by jctanner** [comment] 2017-10-04 13:52
@dougm no problem. Hopefully I've given you enough to go on.

**Comment by dougm** [comment] 2017-10-04 16:49
@jctanner yes indeed, fix is merged.

**Closed** 2017-10-04 16:48 UTC

**Comment by Akasurde** [comment] 2017-10-04 17:27
@dougm Thanks.
