### ISSUE TITLE
Go 1.16: `go install` fails

### ISSUE THREAD

**Issue by sodul** [vmware/govmomi#2345] opened 2021-04-01 08:14 UTC
After upgrading to `go 1.16` we are unable to install the vcsim package:
```
# go install github.com/vmware/govmomi/vcsim@v0.24.1
go install github.com/vmware/govmomi/vcsim@v0.24.1: github.com/vmware/govmomi@v0.24.1
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
root@bfb75838d827:/go# 
```

We could use `go get`, it works, but installing through `go get` behaves differently and installing with `go get` is officially deprecated.

**Comment by embano1** [comment] 2021-04-01 10:00
This might be caused by some restrictions currently in place for the new `go install` behavior in v1.16:

```
In order to eliminate ambiguity about which versions are used, there are several restrictions on what directives may be present in the program's go.mod file when using this install syntax. In particular, replace and exclude directives are not allowed, at least for now. In the long term, once the new go install program@version is working well for enough use cases, we plan to make go get stop installing command binaries. See issue 43684 for details.
```

https://blog.golang.org/go116-module-changes

Does `go get` work for you as a workaround for now?

```bash
go get -u -v github.com/vmware/govmomi/govc@v0.24.1
```

**Comment by sodul** [comment] 2021-04-01 18:26
Yes, `go get` works for now but it will not in future versions of Go so we want to make sure govmomi will be forward compatible.

A concern is that if we use `go get` in a directory with a `go.mod` file it will possibly update it which is undesirable side. We have a custom wrapper to install go tools and we are selectively using `go install`, `gobin` and `go get` as other projects have issues with `go install` and Go 1.16.

Overall not a blocker from us, at least until Go 1.17 or whatever version will no longer let `go get` install things.

**Comment by embano1** [comment] 2021-04-01 18:40
Perhaps the following can help in the short/mid term:

1) Use `mod=vendor` (which is default if `vendor` folder is found) or `readonly` to prevent accidental updates of `go.mod`
2) We are currently in the process of completely updating and automating the release process. You can see that with the Github Actions run using go 1.15/1.16 matrix tests. The builds for release artefacts will likely use go 1.16 once we ship it.

Would be great to get your feedback and perspective if consuming binaries vs building your own is something you prefer.

**Comment by sodul** [comment] 2021-04-06 16:09
@embano1 we have a wrapper around all our `go install` calls and we call `go get` for this one target. The wrapper takes care to switch to a temporary directory so that our development directories remain unaffected. This mean we are fine for now.

As far as binary releases are concerned, that would be convenient especially if you can embed the version in the final binary, but this is not a strong requirement for us since `go get` is relatively snappy.

**Comment by embano1** [comment] 2021-04-06 20:53
Perfect then! Check out this PR which will get you the binaries and more detailed version information for govc/vcsim: https://github.com/vmware/govmomi/pull/2340

**Comment by embano1** [comment] 2021-04-14 20:50
Related: #2357

**Comment by embano1** [comment] 2021-05-05 11:47
@sodul is it ok to close this one?

**Comment by sodul** [comment] 2021-05-09 01:48
I suppose since there is a workaround with `go get` but that might fail in the future. We'll take a look at the binary release in the future, but for now we have a working setup.

**Closed** 2021-05-09 06:02 UTC
