### ISSUE TITLE
[BUG] Data race in simulator.EventManager.PostEvent

### ISSUE THREAD

**Issue by awsaba** [vmware/govmomi#2650] opened 2021-11-05 18:00 UTC
**Describe the bug**

**To Reproduce**

1. Run tests with higher count: `TEST_COUNT=10 make test`
1. The data race will occasionally be detected on different tests.

**Expected behavior**

No data race detected.

**Affected version**

This occurs on current master@14d8083c9ca296ce3c3e6d4fe21e455119f56db5, with go 1.16 and 1.17.

**Screenshots/Debug Output**

This run it occurred on TestDataCenterPowerOnMultiVMs, but other common tests include Test

```
=== RUN   TestDatacenterPowerOnMultiVMs
==================
WARNING: DATA RACE
Read at 0x00c0001c2d68 by goroutine 106:
  github.com/vmware/govmomi/simulator.(*EventManager).PostEvent()
      /Users/asaba/projects/govmomi/simulator/event_manager.go:159 +0x6b
  github.com/vmware/govmomi/simulator.(*Context).postEvent.func1()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:390 +0xeb
  github.com/vmware/govmomi/simulator.(*Registry).WithLock()
      /Users/asaba/projects/govmomi/simulator/registry.go:630 +0x5e
  github.com/vmware/govmomi/simulator.(*Context).WithLock()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:382 +0xe4
  github.com/vmware/govmomi/simulator.(*Context).postEvent()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:388 +0x18
  github.com/vmware/govmomi/simulator.(*powerVMTask).Run()
      /Users/asaba/projects/govmomi/simulator/virtual_machine.go:1461 +0x85c
  github.com/vmware/govmomi/simulator.(*powerVMTask).Run-fm()
      /Users/asaba/projects/govmomi/simulator/virtual_machine.go:1437 +0x44
  github.com/vmware/govmomi/simulator.(*Task).Run.func1()
      /Users/asaba/projects/govmomi/simulator/task.go:112 +0x9e

Previous write at 0x00c0001c2d68 by goroutine 25:
  github.com/vmware/govmomi/simulator.(*EventManager).PostEvent()
      /Users/asaba/projects/govmomi/simulator/event_manager.go:159 +0x8a
  github.com/vmware/govmomi/simulator.(*Context).postEvent.func1()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:390 +0xeb
  github.com/vmware/govmomi/simulator.(*Registry).WithLock()
      /Users/asaba/projects/govmomi/simulator/registry.go:630 +0x5e
  github.com/vmware/govmomi/simulator.(*Context).WithLock()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:382 +0xe4
  github.com/vmware/govmomi/simulator.(*Context).postEvent()
      /Users/asaba/projects/govmomi/simulator/session_manager.go:388 +0x18
  github.com/vmware/govmomi/simulator.(*powerVMTask).Run()
      /Users/asaba/projects/govmomi/simulator/virtual_machine.go:1461 +0x85c
  github.com/vmware/govmomi/simulator.(*powerVMTask).Run-fm()
      /Users/asaba/projects/govmomi/simulator/virtual_machine.go:1437 +0x44
  github.com/vmware/govmomi/simulator.(*Task).Run.func1()
      /Users/asaba/projects/govmomi/simulator/task.go:112 +0x9e
```

**Additional context**

**Comment by dougm** [comment] 2021-11-05 18:59
I had started to look at this yesterday, caused by a combo of 4b59b652 (async tasks) and the more recent #2586
The patch below avoids the race, I'll try to take a closer look over the weekend and open a PR.

```diff
modified   simulator/datacenter.go
@@ -167,7 +167,9 @@ func (dc *Datacenter) PowerOnMultiVMTask(ctx *Context, req *types.PowerOnMultiVM
 			// (equivalent to vSphere DRS).
 			ctx.WithLock(vm, func() {
 				vmTaskBody := vm.PowerOnVMTask(ctx, &types.PowerOnVM_Task{}).(*methods.PowerOnVM_TaskBody)
-				res.Attempted = append(res.Attempted, types.ClusterAttemptedVmInfo{Vm: ref, Task: &vmTaskBody.Res.Returnval})
+				task := vmTaskBody.Res.Returnval
+				ctx.Map.Get(task).(*Task).Wait() // need to let the task complete while we hold the vm lock
+				res.Attempted = append(res.Attempted, types.ClusterAttemptedVmInfo{Vm: ref, Task: &task})
 			})
 		}
```

**Comment by awsaba** [comment] 2021-11-05 21:02
This is going to happen with any test or workload that has multiple concurrent go routines trying to post events, so I've pushed potential fix https://github.com/vmware/govmomi/pull/2651 that puts a mutex on the method.

**Comment by akutz** [comment] 2021-11-05 21:38
Thanks for IDing this issue. I'll also take a look later if it's not already merged.

**Closed** 2021-11-09 20:34 UTC
Labels: kind/bug, area/vcsim
