### ISSUE TITLE
Virtual machine console

### ISSUE THREAD

**Issue by sirzhanghai** [vmware/govmomi#1526] opened 2019-07-18 03:06 UTC
Hello, I need your help.
Does Vcenter web interface require login to access virtual machine console routing?;
Sign up for 401. How to solve if the verification fails

**Comment by dougm** [comment] 2019-07-20 15:59
@sirzhanghai why open a separate issue?  Closing this as a duplicate of #1512

**Closed by dougm** 2019-07-20 15:59 UTC
