### ISSUE TITLE
[BUG] govc v0.37.2 command vm.disk.change always fail

### ISSUE THREAD

**Issue by Fred78290** [vmware/govmomi#3454] opened 2024-05-30 09:06 UTC
**Describe the bug**
After update to govc **v0.37.2** the command **vm.disk.change** always fail 
The version v0.37.1 works correctly

**To Reproduce**

1. Import OVA ubuntu: https://cloud-images.ubuntu.com/noble/current/noble-server-cloudimg-amd64.ova
2. govc vm.disk.change -vm noble-server-cloudimg-amd64 -size=20G

**Expected behavior**
Resize disk to the expected size

**Affected version**
v0.37.2 on MacOS + Linux.

**Screenshots/Debug Output**
`
govc: error resizing main disk
Logged Item:  Invalid operation for device '0'.
`

**Additional context**
command installed with these method

1. curl -L -o - https://github.com/vmware/govmomi/releases/download/v0.37.2/govc_Darwin_arm64.tar.gz | tar -C /usr/local/bin -xvzf - govc
2. go install github.com/vmware/govmomi/govc@latest

**Comment by tenthirtyam** [comment] 2024-06-01 03:51
Duplicate of #3441

**Closed by tenthirtyam** 2024-06-01 03:51 UTC
