### ISSUE TITLE
guest.ls only works once after each VM reboot

### ISSUE THREAD

**Issue by amitbet** [vmware/govmomi#830] opened 2017-08-30 07:26 UTC
When I run a remote command on the guest osx (MacOS Sierra) VM via govc guest.start or guest.ps 
It will run fine for the first time after VM boot, but for any following command it will write:

> **govc.exe: ServerFaultCode: Failed to authenticate with the guest operating system using the supplied credentials.**

This is obviously some other problem, since my credentials were fine for the first run with the exact same commandline, and will be ok again if I shut down and restart the machine.

**I am using vSphere 6.0 (Version 6.0.0 Build 5112533)
I tested it with Govc 0.15 win64 as well as OSX64.**

So After reboot:
----------------------
C:\Users\Administrator>govc.exe guest.ls -l=user:"Password" -vm="sierra2" /tmp
lrwxrwxrwx  0  0  0  Aug 29 15:05 2017  /tmp

C:\Users\Administrator>govc.exe guest.ls -l=user:"Password" -vm="sierra2" /tmp
govc.exe: ServerFaultCode: Failed to authenticate with the guest operating system using the supplied credentials.

**Comment by dougm** [comment] 2017-09-06 22:17
Is this the version of tools that comes with 6.0 or something you built from open-vm-tools?  Not sure what the cause would be, but don't think it would be on the govc side.

Depending on your use-case, maybe using the Go toolbox is an option: https://github.com/vmware/govmomi/tree/master/toolbox

**Comment by dougm** [comment] 2017-10-16 16:27
Don't see how this could be a govmomi or govc issue, closing for now.  Feel free to update / re-open with any other info.

**Closed by dougm** 2017-10-16 16:27 UTC
