### ISSUE TITLE
mem.reservation cannot be set to any value other than the memory declared

### ISSUE THREAD

**Issue by weikinhuang** [vmware/govmomi#1871] opened 2020-03-17 23:07 UTC
I'm trying to set memory allocation with `vm.change` to `0` using the `govc` cli tool

I'm creating the vm by cloning a packer template
```
    govc vm.clone \
        -k \
        -on=false \
        -link=false \
        -vm packer-template \
        -c 4 \
        -m 4096 \
        foo-vm
```

But by default memory allocation is set to the value of the memory `4096`.
Before I power it on, i'm trying to use `vm.change` to change the reservation to `0`, but it errors out:

```
$ govc vm.change -vm foo-vm -mem.reservation 0
govc: A specified parameter was not correct: spec.memoryAllocation.reservation
```

I get this same error if I try any value other than `4096`.

I also tried using `-e`, but has no effect
```
    govc vm.change -vm foo-vm \
        -e sched.mem.min=0 \
        -e sched.mem.minSize=0
```

I also can't unset the value `sched.mem.pin = "TRUE"` (`Reserve all guest memory (All locked)`) with `govc`

**Comment by dougm** [comment] 2020-03-19 23:20
Can you reproduce this using `vm.create` + `vm.clone` ?  Works for me:

```console
% govc vm.create -on=false -c 4 -m 4096 template-vm

% govc vm.change -vm template-vm -mem.reservation 4096

% govc vm.clone -on=false -link=false -vm template-vm -c 4 -m 4096 test-vm

% govc object.collect -s vm/test-vm summary.config.memoryReservation
4096

% govc vm.change -vm test-vm -mem.reservation 0

% govc object.collect -s vm/test-vm summary.config.memoryReservation
0
```

**Comment by dougm** [comment] 2020-03-19 23:28
Can you review #1876 for the memory-pin option?

**Comment by weikinhuang** [comment] 2020-03-19 23:43
Yes, the `mem.reservation` works after I manually disable `Lock all memory` in the UI.

**Comment by dougm** [comment] 2020-03-22 14:55
ok closing with #1876 merged, feel free to re-open if this is still an issue.

**Closed by dougm** 2020-03-22 14:55 UTC
Labels: area/govc
