### ISSUE TITLE
govc datastore.mv command fails to move VMDK file if source file and destination file names are different

### ISSUE THREAD

**Issue by sumitmaggo** [vmware/govmomi#2222] opened 2020-12-28 14:14 UTC
On VMWare ESXi host, if we try to move VMDK file using govc datastore.mv command, it fails if the source vmdk filename and destination vmdk filename are different.

Error: Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/TEST1/sample_test.vmdk

```
$ govc version
govc 0.20.0

When source and destination vmdk file names are same - It works :
On VMWare ESXi host:
$ pwd
/vmfs/volumes/datastore1
$ ls -ltr TEST/sample.vmdk
-rw-r--r--    1 root     root     1976543232 Dec 28 06:04 TEST/sample.vmdk
$ ls -ltr TEST1
total 0

From Linux server where govc is installed:
$ govc datastore.mv TEST/sample.vmdk TEST1/sample.vmdk
[28-12-20 09:09:17] Moving [datastore1] TEST/sample.vmdk to [datastore1] TEST1/sample.vmdk...OK

On VMWare ESXi Host after above move:
$ pwd
/vmfs/volumes/datastore1
$ ls -ltr TEST/
total 0
$ ls -ltr TEST1/
total 1930240
-rw-r--r--    1 root     root     1976543232 Dec 28 06:04 sample.vmdk


When source and destination vmdk file names are different - It fails :
On VMWare ESXi host:
$ pwd
/vmfs/volumes/datastore1
$ ls -ltr TEST/sample.vmdk
-rw-r--r--    1 root     root     1976543232 Dec 28 06:04 TEST/sample.vmdk
$ ls -ltr TEST1
total 0

From Linux server where govc is installed:
$ govc datastore.mv TEST/sample.vmdk TEST1/sample_test.vmdk
[28-12-20 09:12:47] Moving [datastore1] TEST/sample.vmdk to [datastore1] TEST1/sample_test.vmdk...Error: Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/TEST1/sample_test.vmdk
govc: Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/TEST1/sample_test.vmdk


On VMWare ESXi Host after above move:
$ pwd
/vmfs/volumes/datastore1
$ ls -ltr TEST/sample.vmdk
-rw-r--r--    1 root     root     1976543232 Dec 28 06:04 TEST/sample.vmdk
$ ls -ltr TEST1
total 0

```

**Comment by dougm** [comment] 2020-12-30 00:37
I can't reproduce using the following:

```console
% govc datastore.mkdir TEST
% govc datastore.disk.create -size 10M TEST/sample.vmdk
[29-12-20 16:31:31] Creating [datastore1] TEST/sample.vmdk...OK
% govc datastore.mv TEST/sample.vmdk TEST/sample_test.vmdk
[29-12-20 16:31:34] Moving [datastore1] TEST/sample.vmdk to [datastore1] TEST/sample_test.vmdk...OK
% govc datastore.ls -l TEST
0B  Wed Dec 30 00:31:34 2020  sample_test.vmdk
```

Against ESXi directly:
```console
% govc about
Name:         VMware ESXi
Vendor:       VMware, Inc.
Version:      7.0.1
Build:        41341759
...
```

Or against vCenter:
```console
% govc about
Name:         VMware vCenter Server
Vendor:       VMware, Inc.
Version:      6.7.0
Build:        17028632
...
```

Can you capture the -debug output, is it may have more details: https://github.com/vmware/govmomi/tree/master/govc#troubleshooting

Or using `govc datastore.mv -xml ...`, output should be the vSphere fault structure with any other details.

**Comment by sumitmaggo** [comment] 2020-12-30 06:13
Thanks @dougm for the response.
I tried the above steps and it worked fine for me as well.
But in my case, the vmdk file which I am trying to move is streamOptimized which is not in expanded form.
For example when we convert any qcow2 file to vmdk file with following options:
qemu-img convert -f qcow2 -O vmdk -o subformat=streamOptimized  CentOS-7-x86_64-GenericCloud-1503.qcow2  CentOS-7-x86_64-GenericCloud-1503.vmdk

The resulting vmdk file is the one that I have uploaded to datastore and then trying to move it to different location in the same datastore.
 
On VMWare ESXi host:
$ pwd
/vmfs/volumes/datastore1
$ ls -ltr TEST/sample.vmdk
-rw-r--r--    1 root     root     1976543232 Dec 28 06:04 TEST/sample.vmdk

As you can see, there is no '-flat.vmdk' disk file and .vmdk file is the stream optimized vmdk file of size 1.9GB.

Attached the debug output from this failed command:
$ govc datastore.mv -debug=true TEST/sample.vmdk TEST1/sample_test.vmdk
[30-12-20 01:06:33] Moving [datastore1] TEST/sample.vmdk to [datastore1] TEST1/sample_test.vmdk...Error: Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/TEST1/sample_test.vmdk
govc: Error caused by file /vmfs/volumes/5bd0b7d5-02d4a3bb-154a-ac162d77f63c/TEST1/sample_test.vmdk

[debug.tar.gz](https://github.com/vmware/govmomi/files/5753194/debug.tar.gz)

**Comment by dougm** [comment] 2020-12-30 18:53
How did you upload sample.vmdk to the datastore?  See also: https://github.com/vmware/govmomi/issues/2039#issuecomment-652448923

**Comment by sumitmaggo** [comment] 2020-12-31 05:39
Here, VMDK file is uploaded using normal file upload method like scp to datastore.
This use case of uploading the vmdk file and then moving it is used by ['vsphere_file'](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/file) resource of terraform.
Since it was giving the same error while moving the file, I tried manually uploading the file using 'scp' to datastore and then moving it using govc datastore.mv command and faced the above error.

**Comment by dougm** [comment] 2021-01-01 19:55
afaik, stream optimized vmdk needs to be converted to run on ESXi, which `import.vmdk` mentioned in the thread above will do.  There isn't anything we can do on the govmomi side to avoid the problem you're having with `datastore.mv` of a stream optimized vmdk.

**Comment by sumitmaggo** [comment] 2021-01-04 06:23
Thanks @dougm for all the support. I will raise a bug on Terraform vsphere provider to get this resolved.

**Comment by dougm** [comment] 2021-01-07 01:07
Looking through the history of `import.vmdk`, it looks like you can create a VM with a streamOptimized vmdk, but I think the disk is converted as part of that process.  And after vmdk conversion, you can use `datastore.mv`: https://github.com/vmware/govmomi/blob/4fa7b32ae55649cd700182a2a19abd7b42f9b0bc/govc/importx/vmdk.go#L278-L298

**Comment by dougm** [comment] 2021-01-08 23:53
Closing as there isn't any change within govmomi we can do to avoid the problem. Please link the Terraform issue here for reference, thanks.

**Closed by dougm** 2021-01-08 23:53 UTC

**Comment by sumitmaggo** [comment] 2021-01-09 09:59
Thanks @dougm for all the help. 
Here is the terraform issue for the reference that is raised on terraform-provider-vsphere code:
https://github.com/hashicorp/terraform-provider-vsphere/issues/1296

**Comment by kofec** [comment] 2021-01-12 12:58
Maybe you can try to use : datastore.upload
