### ISSUE TITLE
Memory usage / garbage collection

### ISSUE THREAD

**Issue by dupondje** [vmware/govmomi#1794] opened 2020-01-14 14:21 UTC
Hi,

I use the following project/tool to fetch VCenter metrics and export them as Prometheus metrics:
https://github.com/cblomart/vsphere-graphite

Now I was troubleshooting the code to improve the speed of the collection (takes around 20 seconds for 500.000 metrics).

There I saw quite some time is spend on GC:
```
(pprof) top10
Showing nodes accounting for 32s, 43.65% of 73.31s total
Dropped 509 nodes (cum <= 0.37s)
Showing top 10 nodes out of 168
      flat  flat%   sum%        cum   cum%
    12.59s 17.17% 17.17%     25.13s 34.28%  runtime.scanobject
     6.04s  8.24% 25.41%      6.68s  9.11%  runtime.findObject
     2.52s  3.44% 28.85%     20.48s 27.94%  runtime.mallocgc
     2.03s  2.77% 31.62%      2.12s  2.89%  runtime.pageIndexOf
     1.83s  2.50% 34.12%      1.83s  2.50%  runtime.markBits.isMarked
     1.56s  2.13% 36.24%      1.94s  2.65%  runtime.heapBitsSetType
     1.54s  2.10% 38.34%      1.54s  2.10%  runtime.memmove
```

If I check the Heap, the following shows a lot of memory usage:
```
(pprof) top10
Showing nodes accounting for 7427.99MB, 89.42% of 8307.12MB total
Dropped 194 nodes (cum <= 41.54MB)
Showing top 10 nodes out of 61
      flat  flat%   sum%        cum   cum%
 3058.40MB 36.82% 36.82%  3259.07MB 39.23%  github.com/vmware/govmomi/vim25/xml.(*Decoder).rawToken
  963.05MB 11.59% 48.41%  4222.12MB 50.83%  github.com/vmware/govmomi/vim25/xml.(*Decoder).Token
  730.03MB  8.79% 57.20%   730.03MB  8.79%  github.com/prometheus/client_golang/prometheus.makeLabelPairs
  693.54MB  8.35% 65.55%  5213.84MB 62.76%  github.com/vmware/govmomi/vim25/xml.(*Decoder).unmarshal
  558.20MB  6.72% 72.27%   581.70MB  7.00%  github.com/cblomart/vsphere-graphite/backend.(*Point).GetTags
  438.56MB  5.28% 77.55%   511.56MB  6.16%  github.com/prometheus/client_golang/prometheus.NewDesc
  312.03MB  3.76% 81.30%  2208.32MB 26.58%  github.com/cblomart/vsphere-graphite/backend.(*Config).PrometheusSend
```

If I check deeper into the github.com/vmware/govmomi/vim25/xml.(*Decoder).rawToken code, it shows huge amount of allocations in the following line:
```
    1.84GB     1.84GB    729:	attr = make([]Attr, 0, 4)
```

Any chance to have some performance improvements here?
Or ask the colleagues to provide a /metrics page for the vcenter :)

**Comment by dougm** [comment] 2020-01-14 18:24
vim25/xml is a fork of Go's encoding/xml package. However, it is still based on Go 1.3.1. There's been some optimizations since then in this area:

https://github.com/golang/go/commit/8f02df76f962e5ea2daf27108a0c8efed2c8d905

https://github.com/golang/go/commit/252ee90971d87f099a2e67c3536a0481a535157f

We can start by updating our fork, and ideally submit some of the changes upstream so we don't have to maintain the fork.

**Comment by dougm** [comment] 2020-01-16 17:03
@dupondje can you try with #1800 to see if it helps? Thanks for sharing the profile data.

**Comment by dupondje** [comment] 2020-01-17 08:23
@dougm : Tested, but it seems to break the whole thing:

could not retrieve object names - ServerFaultCode: Unexpected exception setting attribute type: N7Vmacore21TypeMismatchExceptionE(Type Mismatch: expected: N5Vmomi17ManagedObjectTypeE, found: N5Vmomi8TypeImplINS_4TypeEEE)
 [context]zKq7AVECAAAAAH6z1gAYdnB4ZAAAoPMqbGlidm1hY29yZS5zbwAAiCAbAC6ZGADumRgAU5oYAaKuGGxpYnZtb21pLnNvAAFh4RgB8/cYAqq9AGxpYmV4cGF0LnNvAAIu1gACf0MBATvoGAExFBcAlvMeAOWRHACOkhwAKoEaAAioJQBplSMAMWIjAPpkIwBdSSsD1HMAbGlicHRocmVhZC5zby4wAAS9jg5saWJjLnNvLjYA[/context]
 while parsing MoRef for ManagedObject of type vmodl.ManagedObject
 at line 2, column 1281
 while parsing property "obj" of static type ManagedObject
 while parsing serialized DataObject of type vmodl.query.PropertyCollector.ObjectSpec
 at line 2, column 1270
 while parsing property "objectSet" of static type ArrayOfObjectSpec
 while parsing serialized DataObject of type vmodl.query.PropertyCollector.FilterSpec
 at line 2, column 161
 while parsing call information for method RetrieveProperties
 at line 2, column 66
 while parsing SOAP body
 at line 2, column 60
 while parsing SOAP envelope
 at line 2, column 0
 while parsing HTTP request for method retrieveContents
 on object of type vmodl.query.PropertyCollector
 at line 1, column 0

**Comment by dougm** [comment] 2020-01-17 20:18
@dupondje apologies, the original port of the patch was broken against vcsim.. after getting it to work against vcsim (make test / Travis CI), I must have not tested against real vCenter again. I see the same issue here and will update here when I'm able to find a proper solution.

For background, the issue is related to this hack:
https://github.com/vmware/govmomi/blob/2944a51b1b90174bd7915f0df399a4c9ea02eb61/vim25/xml/read.go#L277-L283

**Comment by dougm** [comment] 2020-01-28 07:06
@dupondje working properly here in both cases now, can you try the updated PR?

**Comment by dupondje** [comment] 2020-01-29 09:24
Still seems to spend some time on GC, but memory usage is WAY better :)
All seems to work fine also. 

Nice improvement! Thanks!

```
(pprof) top10
Showing nodes accounting for 28.76s, 41.56% of 69.20s total
Dropped 528 nodes (cum <= 0.35s)
Showing top 10 nodes out of 168
      flat  flat%   sum%        cum   cum%
    10.97s 15.85% 15.85%     22.71s 32.82%  runtime.scanobject
     5.83s  8.42% 24.28%      6.28s  9.08%  runtime.findObject
     2.17s  3.14% 27.41%     16.93s 24.47%  runtime.mallocgc
     1.91s  2.76% 30.17%      2.02s  2.92%  runtime.pageIndexOf
     1.57s  2.27% 32.44%      1.57s  2.27%  runtime.markBits.isMarked
     1.32s  1.91% 34.35%      1.32s  1.91%  github.com/prometheus/client_model/go.(*LabelPair).GetName
     1.31s  1.89% 36.24%      1.31s  1.89%  runtime.memmove
     1.27s  1.84% 38.08%      1.61s  2.33%  github.com/cblomart/vsphere-graphite/vsphere.(*Cache).CleanAll
     1.26s  1.82% 39.90%      1.73s  2.50%  runtime.heapBitsSetType
     1.15s  1.66% 41.56%      1.39s  2.01%  bufio.(*Reader).ReadByte
```

```
(pprof) top10
Showing nodes accounting for 441.63MB, 98.85% of 446.75MB total
Dropped 29 nodes (cum <= 2.23MB)
Showing top 10 nodes out of 36
      flat  flat%   sum%        cum   cum%
  325.51MB 72.86% 72.86%   325.51MB 72.86%  github.com/prometheus/client_golang/prometheus.makeLabelPairs
   62.60MB 14.01% 86.87%    87.60MB 19.61%  github.com/prometheus/client_golang/prometheus.processMetric
      25MB  5.60% 92.47%       25MB  5.60%  github.com/prometheus/client_golang/prometheus.populateMetric
      12MB  2.69% 95.16%       12MB  2.69%  strings.(*Builder).grow
       7MB  1.57% 96.72%        7MB  1.57%  github.com/vmware/govmomi/vim25/xml.(*Decoder).name
    4.52MB  1.01% 97.73%     6.02MB  1.35%  github.com/cblomart/vsphere-graphite/vsphere.(*Cache).add
    2.50MB  0.56% 98.29%     8.52MB  1.91%  github.com/cblomart/vsphere-graphite/vsphere.(*Cache).Add
    2.50MB  0.56% 98.85%     2.50MB  0.56%  github.com/vmware/govmomi/vim25/xml.copyValue
         0     0% 98.85%   337.51MB 75.55%  github.com/cblomart/vsphere-graphite/backend.(*Config).Collect
         0     0% 98.85%   337.51MB 75.55%  github.com/cblomart/vsphere-graphite/backend.(*Config).PrometheusSend
```

**Comment by dougm** [comment] 2020-01-29 14:08
Thanks @dupondje , good news on the memory usage. If we were to make further improvements to the xml package, it should be in the upstream Go package instead.  We should also spend some time to integrate the vim25/xml patches upstream so we don't have to maintain this fork anymore. Given that and #1800 is merged, I'll close this issue.

**Closed by dougm** 2020-01-29 14:08 UTC
Labels: area/client, kind/quality
