### ISSUE TITLE
GOVC 22.1 /ESX 6.7U3 - Import OVA fails for the 4th OVA image

### ISSUE THREAD

**Issue by linuxcrash** [vmware/govmomi#2004] opened 2020-06-05 13:15 UTC
I'm using GOVC 22.1 to import the Fedora CoreOS OVA multiple times after each other (Deploying 4 VMs). At some point GOVC is successfully importing the OVA file and a VM gets created but there is a stuck task in vSphere WebUI showing that the import is not finished. All subsequent operations on the same VM (Change properties or power it on) fail. Cancelling the task in the WebUI it deletes the VM.

GOVC: 22.1
ESX 6.7U3 Standalone (no VCSA) but license applied.

GOVC output:
![grafik](https://user-images.githubusercontent.com/5081159/83880356-4e7fd480-a73f-11ea-9099-21abf1518176.png)

All I found is the below messages in the hostd logfile:
`2020-06-05T12:34:46.506Z warning hostd[2100145] [Originator@6876 sub=PropertyCollector opID=esxui-a03e-26da user=root] Session 524173e5-2387-a5b6-d701-0a051e649c3b has issued 2 concurrent blocking calls to the property collector. This is almost certainly an error in the logic of the client application.`

**Comment by dougm** [comment] 2020-06-11 23:55
Is this something you can reproduce easily and provide the steps?

Looks like that error is from the UI (esxui), don't think that's related.

**Comment by dougm** [comment] 2020-09-12 19:02
Closing as can't reproduce, feel free to re-open with detailed steps to reproduce.

**Closed by dougm** 2020-09-12 19:02 UTC
