### ISSUE TITLE
govc guest.upload command fails with "dial tcp X.X.X.X i/o timeout"

### ISSUE THREAD

**Issue by kasper5** [vmware/govmomi#905] opened 2017-10-30 07:12 UTC
Hi,

When I use the guest.upload command it fails with the following error msg:

`govc: Put https://10.94.254.36:443/guestFile?id=6&token=5236206b-7183-db49-c155-4c7452335a7d6: dial tcp 10.94.254.36:443: i/o timeout`

Anyone know why?

**Comment by anfernee** [comment] 2017-10-30 17:55
I cannot reproduce this issue. Is your esx server working? If you curl it, you should be able to get a html page back.

```
$ curl -k https://10.20.72.160
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">

<html lang="en">
<head>
    <meta http-equiv="content-type" content="text/html; charset=utf8">
    <meta http-equiv="refresh" content="0;URL='/ui'"/>
</head>
</html>
```

**Comment by dougm** [comment] 2017-11-08 15:01
The `InitiateFileTransferToGuest` returns a URL with the ESX HostSystem name where the VM is currently running.  We've had issues in the past using the name, so we use a management IP instead:

https://github.com/vmware/govmomi/blob/b227a2582a9e5175fc778fc6a03b98aa14534927/guest/file_manager.go#L168-L171

Sounds like you don't have a route to that IP from where you're running govc.  Does the curl command work using the host name?
```
curl -k https://$(govc vm.info YOUR-VM-NAME | grep Host: | awk '{print $2}')
```

Or any of these IPs:
```
govc host.info -json $(govc vm.info YOUR-VM-NAME | grep Host: | awk '{print $2}' | xargs govc find / -type h -name) | jq -r '.HostSystems[].Config.VirtualNicManagerInfo.NetConfig[] | select(.NicType == "management") | .CandidateVnic[].Spec.Ip.IpAddress'
```

**Comment by kasper5** [comment] 2017-11-09 07:05
Thank you both for your responses. I am able to reach the esxi hosts just fine so I don't think there's any route problems. 

If I do:

`curl -k https://10.94.254.37`

I get:

![screenshot_2017-11-09_08-02-34](https://user-images.githubusercontent.com/11734075/32592551-8a18df28-c524-11e7-9978-8a9ba19871a6.png)

I forgot to mention that the ESXi hosts is currently running in evaluation mode, could this be the problem?

**Comment by kasper5** [comment] 2017-11-10 09:27
I just retested on a different OS (Ubuntu) and everything works great. I only get the error when I am running it from a FreeBSD jail (sorry probably should have mention this before), is there some limitations on using govc inside a FreeBSD jail?

**Comment by dougm** [comment] 2017-11-15 05:11
govmomi/govc doesn't know anything about jails.  Does the curl command work from the jail?

**Comment by dougm** [comment] 2017-12-17 17:27
Closing as this sounds like an issue with the jail, rather than govmomi.  Feel free to open with more info if you want to look into it more.

**Closed by dougm** 2017-12-17 17:27 UTC

**Comment by tigerdice** [comment] 2019-12-06 08:09
Running this command
govc import.ovf -name "ubuntu-03" -k=true -dc=/somedc -ds=datastore_S_001 -pool=/somedc /host/somecluster/Resources/rpl_IaC001 -folder=/somedc/vm/USER/T3/IaC_ai001/templates_ai001/ image.ovf

Uploading image-disk1.vmdk... Error: Post https://xxx.xx.xxx.com/nfc/5242dd2e-9e59-e1d2-bfe9-e7f1850f47a5/disk-0.vmdk: dial tcp xx.xx.xxx.41:443: i/o timeout

In the vcenter for a short time i can see the vm there but without disk and nvram.
